spring:
  application:
    name: rate-limiter
  cache:
    cache-names: rateLimiterRules

rate-limiter:
  cache:
    time-to-live:
      rate-limiter-rules: 300
  rules:
    destination: classpath:rate-limiter-rules.json