spring:
  application:
    name: rate-limiter
  cache:
    cache-names: rateLimiterRules

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

rate-limiter:
  cache:
    time-to-live:
      rate-limiter-rules: 300
  rules:
    destination: classpath:rate-limiter-rules.json